version: "2"

run:
  build-tags:
    - rapidsnark_noasm

linters:
  default: none
  enable:
    - bodyclose
    - dupl
    - errcheck
    - gochecknoinits
    - gocritic
    - gocyclo
    - gosec
    - govet
    - ineffassign
    - misspell
    - nakedret
    - prealloc
    - revive
    - staticcheck
    - unconvert
    - unparam
    - unused
    - lll
    - goconst
  settings:
    goconst:
      min-len: 2
      min-occurrences: 2
    gocritic:
      disabled-checks:
        - hugeParam
      enabled-tags:
        - performance
        - style
        - experimental
    govet:
      enable:
        - shadow
    lll:
      line-length: 160
    misspell:
      locale: US
    revive:
      confidence: 0.1
      rules:
        # Add more comments for exported functions and remove this rule
        - name: package-comments
          disabled: true
  exclusions:
    generated: lax
    rules:
      - linters:
          - staticcheck
        text: at least one file in a package should have a package comment
      - linters:
          - revive
        text: should have a package comment, unless it's in another file for this package
      - linters:
          - dupl
          - gosec
          - lll
        path: _test\.go
formatters:
  enable:
    - gofmt
    - goimports
    - gci
