name: test

on:
  push:
    branches:
      - main
      - develop
  pull_request:

jobs:
  test:
    strategy:
      matrix:
        go-version: [ 1.18.x ]
    runs-on: ubuntu-latest
    steps:
      - name: Install Go
        if: success()
        uses: actions/setup-go@v2
        with:
          go-version: ${{ matrix.go-version }}
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Run tests
        run: go test -v -covermode=count

