name: test

on:
  push:
    branches:
      - main
      - develop
  pull_request:
    branches:
      - main
      - develop

jobs:
  test:
    strategy:
      matrix:
        go-version: [ 1.18.x ]
    runs-on: ubuntu-22.04
    steps:
      - name: Install Go
        if: success()
        uses: actions/setup-go@v2
        with:
          go-version: ${{ matrix.go-version }}
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Run tests
        # noasm build tag is needed for older GitHub Action runners
        run: go test -tags noasm -v -covermode=count

