name: test

on:
  push:
    branches:
      - main
      - develop
  pull_request:

jobs:
  test:
    strategy:
      matrix:
        go-version:
        - 1.18.x
        - 1.19.x
        - 1.20.x
        - 1.21.x
    runs-on: ubuntu-22.04
    steps:
      - name: Install Go
        if: success()
        uses: actions/setup-go@v2
        with:
          go-version: ${{ matrix.go-version }}
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Run tests
        # rapidsnark_noasm build tag is needed for older GitHub Action runners
        run: go test -tags rapidsnark_noasm -v -covermode=count

